version: '3.3'
services:
  database:
    image: 'postgres:15'
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: alten-user
      POSTGRES_PASSWORD: alten-password
      POSTGRES_DB: alten-db
    volumes:
      - postgres-test-volume-data:/var/lib/postgresql/data
volumes:
  postgres-test-volume-data: